name: Data link to OxCGRT
on:
 push
# schedule:
#   - cron: '1 2-23 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Download raw csv from OxCGRT database
        run: |
          curl 'https://oxcgrtportal.azurewebsites.net/api/CSVDownload?type=Compressed' -s -f -o 'legacy_data_202207/OxCGRT_latest.csv'
          curl 'https://oxcgrtportal.azurewebsites.net/api/CSVDownload?type=changes_responses' -s -f -o 'legacy_data_202207/OxCGRT_latest_responses.csv'
          curl 'https://oxcgrtportal.azurewebsites.net/api/CSVDownload?type=changes_all' -s -f -o 'legacy_data_202207/OxCGRT_latest_allchanges.csv'
          curl 'https://oxcgrtportal.azurewebsites.net/api/CSVDownload?type=combined' -s -f -o 'legacy_data_202207/OxCGRT_latest_combined.csv'
          curl 'https://oxcgrtportal.azurewebsites.net/api/csvdownload?type=vaccine_full' -s -f -o 'legacy_data_202207/OxCGRT_vaccines_full.csv'
          curl 'https://oxcgrtportal.azurewebsites.net/api/CSVDownload' -s -f -o 'legacy_data_202207/OxCGRT_withnotes.csv'
          awk -F "," 'NR==1 {header=$0}; NF>1 && NR>1 {year=substr($6,1,4); if(! files[year]) {print header > ("legacy_data_202207/OxCGRT_withnotes_" year ".csv"); files[year]=1}; print $0 > ("legacy_data_202207/OxCGRT_withnotes_" year ".csv")}' 'legacy_data_202207/OxCGRT_withnotes.csv'
          rm 'legacy_data_202207/OxCGRT_withnotes.csv'
          
      - name: Commit changes
        run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git add .
         git diff-index --quiet HEAD || git commit -m "OxCGRT Data Update" -a
         git push origin main:main
